name: Automatic tests

on: [push, pull_request]

jobs:
  make_test:
    name: make test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install swivm and SWI-Prolog
      uses: fnogatz/swivm/actions/load@main
      with:
        swi-prolog-version: 8.0

    - name: Install SWI-Prolog pack dependencies
      run: |
        source ~/.swivm/swivm.sh
        ln -s $(pwd) $(swivm current --pack)/xsd
        make install SWIPL=$(swivm which)

    - name: Run tests
      run: |
        source ~/.swivm/swivm.sh
        make test SWIPL=$(swivm which)
